apiVersion: v1
kind: Pod
metadata:
  name: shell-demo
spec:
  containers:
      - name: main
        image: amazonlinux:2
        command:
          - "sh"
          - "-c"
          - "yum install -y python3-pip && tail -f /var/log/yum.log"
        resources:
          limits: 
            memory: "500Mi"
            cpu: "0.25"